---
- name: Ensure mongo toolchain directory exists
  become: true
  file:
    path: "{{ mongo_toolchain_revisions_directory }}"
    state: directory

- name: Rename mongodbtoolchain directory
  become: true
  command: mv /tmp/{{ toolchain_top_level_directory }} {{ mongo_toolchain_revisions_directory }}
  args:
    creates: "{{ mongo_toolchain_revisions_directory }}/{{ toolchain_top_level_directory }}"
  when:
    - toolchain_archive_contents.changed

- name: Run mongodb toolchain install script
  become: true
  command: "{{ mongo_toolchain_revisions_directory }}/{{ toolchain_top_level_directory }}scripts/install.sh"
  args:
    creates: "{{ mongo_toolchain_final_dest }}/v3"
  when:
    - toolchain_archive_contents.changed
