---
- name: Ensure mongo toolchain directory exists
  become: true
  file:
    path: "{{ mongo_toolchain_revisions_directory }}"
    state: directory
    mode: 0755

- name: Rename mongodbtoolchain directory
  become: true
  command: mv /tmp/{{ toolchain_top_level_directory }} {{ mongo_toolchain_revisions_directory }}
  args:
    creates: "{{ mongo_toolchain_revisions_directory }}/{{ toolchain_top_level_directory }}"
  when:
    - toolchain_archive_contents.changed

- name: Run mongodb toolchain install script
  become: true
  command: "{{ mongo_toolchain_revisions_directory }}/{{ toolchain_top_level_directory }}scripts/install.sh"
  args:
    creates: "{{ mongo_toolchain_final_dest }}/v3"
  when:
    - toolchain_archive_contents.changed

- name: Create version file [{{ mongo_toolchain_sha }}]
  become: true
  copy:
    content: "{{ mongo_toolchain_sha }}"
    dest: "{{ mongo_toolchain_final_dest }}/toolchain_version"
    mode: 0644

- name: Fix toolchain permissions | Make /opt/mongodbtoolchain write-able by evergreen user
  become: true
  file:
    state: directory
    recurse: true
    # Make it so no one can destroy or modify the toolchain by accident
    mode: 0755
    path: /opt/mongodbtoolchain
    owner: "{{ mongo_toolchain_evergreen_user }}"
