---
- name: Ensure mongo toolchain directory exists
  become: true
  file:
    path: "{{ mongo_toolchain_revisions_directory }}"
    state: directory

- name: Rename mongodbtoolchain directory
  become: true
  command: mv {{ mongo_toolchain_dest }}/{{ toolchain_top_level_directory }} {{ mongo_toolchain_revisions_directory }}
  args:
    creates: "{{ mongo_toolchain_revisions_directory }}/{{ toolchain_top_level_directory }}"
  when: toolchain_top_level_directory is defined

- include_tasks: setup-Debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: setup-Darwin.yml
  when: ansible_os_family == "Darwin"
