---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: amazon
    image: amazonlinux
  - name: debian9
    image: debian:9
  - name: debian10
    image: debian:10
  - name: rhel7
    image: registry.redhat.io/ubi7
  - name: rhel8
    image: registry.redhat.io/ubi8
  - name: ubuntu1604
    image: ubuntu:16.04
  - name: ubuntu1804
    image: ubuntu:18.04
  - name: ubuntu2004
    image: ubuntu:20.04
  - image: ppc64le/centos
    name: centos-ppc64le
  - image: ppc64le/debian
    name: debian-ppc64le
  - image: s390x/clefos
    name: centos-s390x
  - image: s390x/debian
    name: debian-s390x
provisioner:
  name: ansible
verifier:
  name: testinfra
